stages:
  - test
  - build

workflow:
  auto_cancel:
    on_new_commit: interruptible

include:
  - local: ".gitlab/ci/tests.yml"
  - local: ".gitlab/ci/terraform.yml"
  - local: ".gitlab/ci/build.yml"
